version: 2
jobs:
  build:
    docker:
      - image: gridlabd/slac-master:latest
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD=yes
          MYSQL_USER=gridlabd
          MYSQL_PASSWORD=gridlabd
          MYSQL_DATABASE=gridlabd
    steps:
      - checkout
      - run:
          name: Install dockerize
          command: yum install wget -y && wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Install mysql client
          command: yum install mysql -y
      - run:
          name: Wait for db
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: Dump the database
          command: mysqldump -h127.0.0.1 -uroot --all-databases > dump.sql 
      - run:
          name: Run the simulation
          command: gridlabd --debug --verbose test_mysql_collector.glm
      - run:
          name: Dump the database
          command: mysqldump -h127.0.0.1 -h-uroot gridlabd > dump.sql 
      - store_artifacts:
          path: /root/project
